<?php
/**
 * Copyright (c) 2026 BluePrint3D Ltd. All rights reserved.
 *
 * This software is provided free of charge for personal or commercial use.
 * Resale, redistribution, or sublicensing of this source code, modified or
 * unmodified, for direct financial gain is strictly prohibited.
 *
 * @author    BluePrint3D Ltd <support@blueprint3d.dev>
 * @copyright 2026 BluePrint3D Ltd (Company No. 13473806)
 * @license   Custom Proprietary EULA (See LICENSE.txt)
 */

/** @var \BluePrint3D\AdminPayment\Block\Info\AdminPayment $block */
$reference = $block->getReference();
?>
<dl class="payment-method">
    <dt class="title"><?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($reference): ?>
    <dd class="content">
        <strong><?= $escaper->escapeHtml(__('Reference')) ?></strong>
        <span class="number"><?= $escaper->escapeHtml($reference) ?></span>
    </dd>
    <?php endif; ?>
</dl>
