<?php
/**
 * Copyright (c) 2026 BluePrint3D Ltd. All rights reserved.
 *
 * This software is provided free of charge for personal or commercial use.
 * Resale, redistribution, or sublicensing of this source code, modified or
 * unmodified, for direct financial gain is strictly prohibited.
 *
 * @author    BluePrint3D Ltd <support@blueprint3d.dev>
 * @copyright 2026 BluePrint3D Ltd (Company No. 13473806)
 * @license   Custom Proprietary EULA (See LICENSE.txt)
 */

/** @var \BluePrint3D\AdminPayment\Block\Info\AdminPayment $block */
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
$reference = $block->getReference();
?>
<div class="order-payment-method-name"><?= $escaper->escapeHtml($paymentTitle) ?></div>
<?php if ($reference): ?>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $escaper->escapeHtml(__('Reference')) ?>:</th>
        <td><?= $escaper->escapeHtml($reference) ?></td>
    </tr>
</table>
<?php endif; ?>
